// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://javaqsqsqkhtvbokqdse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphdmFxc3FzcWtodHZib2txZHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyOTU4ODMsImV4cCI6MjA0OTg3MTg4M30.fe4uPvkK2qnjbdUDE_XowTGlzbi838pB8ES6uOcoPZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);